#!/usr/bin/env bash

# Change theming from dark to light or vice versa

if [[ $(dconf read /org/gnome/desktop/interface/color-scheme) == "'prefer-dark'" ]]; then
  dconf write /org/gnome/desktop/interface/color-scheme "'prefer-light'"
  dconf write /org/gnome/desktop/interface/gtk-theme "'adw-gtk3'"
else
  dconf write /org/gnome/desktop/interface/color-scheme "'prefer-dark'"
  dconf write /org/gnome/desktop/interface/gtk-theme "'adw-gtk3-dark'"
fi
